# Generated by Django 5.2.17 on 2026-08-18 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_water_liters', models.DecimalField(decimal_places=2, max_digits=14)),
                ('simulated_water_liters', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reduction_percentage', models.DecimalField(decimal_places=2, help_text='e.g. 10.0, 20.0, 30.0, 50.0', max_digits=5)),
                ('total_fields_count', models.IntegerField(default=0)),
                ('affected_fields_count', models.IntegerField(default=0)),
                ('major_affected_field', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('action_plan_snapshot', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_simulation_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
