# Generated by Django 5.2.16 on 2026-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croptype',
            name='crop_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='croptype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
