# Generated by Django 5.2.16 on 2026-09-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_croptype_crop_value_croptype_status_soiltype_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='master.croptype')),
            ],
            options={
                'db_table': 'tbl_crop_variety',
                'ordering': ['crop__name', 'variety_name'],
                'unique_together': {('crop', 'variety_name')},
            },
        ),
        migrations.CreateModel(
            name='CropWaterRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_stage', models.CharField(choices=[('germination', 'Germination'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvesting', 'Harvesting')], default='vegetative', max_length=30)),
                ('min_water', models.DecimalField(decimal_places=2, help_text='Minimum water requirement (L/m²/day)', max_digits=8)),
                ('max_water', models.DecimalField(decimal_places=2, help_text='Maximum water requirement (L/m²/day)', max_digits=8)),
                ('optimal_water', models.DecimalField(decimal_places=2, help_text='Optimal baseline water requirement (L/m²/day)', max_digits=8)),
                ('unit', models.CharField(default='L/m²/day', max_length=30)),
                ('source_reference', models.TextField(blank=True, help_text='Agricultural research source or reference (e.g. ICAR / FAO 56)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_requirements', to='master.croptype')),
                ('soil_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_requirements', to='master.soiltype')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_requirements', to='master.cropvariety')),
            ],
            options={
                'db_table': 'tbl_crop_water_requirement',
                'ordering': ['crop__name', 'variety__variety_name', 'crop_stage'],
                'constraints': [models.UniqueConstraint(fields=('crop', 'variety', 'crop_stage', 'soil_type'), name='unique_crop_variety_stage_soil')],
            },
        ),
    ]
