# Generated by Django 5.2.16 on 2026-09-14 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_cropvariety_cropwaterrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropVarietyStageDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('germination', 'Germination'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('harvesting', 'Harvesting')], max_length=30)),
                ('start_day', models.PositiveIntegerField(help_text='Start day after planting (inclusive, starting at 0)')),
                ('end_day', models.PositiveIntegerField(blank=True, help_text='End day after planting (inclusive). Leave blank/null for open-ended final harvesting stage.', null=True)),
                ('source_reference', models.TextField(blank=True, help_text='Agricultural research reference for verified stage duration (e.g. KAU Package of Practices 2024 / ICAR)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_durations', to='master.cropvariety')),
            ],
            options={
                'db_table': 'tbl_crop_variety_stage_duration',
                'ordering': ['crop_variety', 'start_day'],
                'constraints': [models.UniqueConstraint(fields=('crop_variety', 'stage'), name='unique_crop_variety_stage')],
            },
        ),
    ]
