# Generated by Django 5.2.17 on 2026-09-15 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_farm_alert_user_alter_alert_field'),
        ('maintenance', '0002_complaint_complaint_id_complaint_complaint_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='maintenance.complaint'),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
