# Generated by Django 4.2 on 2026-07-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Celsius', max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('rainfall', models.DecimalField(decimal_places=2, default=0, help_text='mm', max_digits=7)),
                ('wind_speed', models.DecimalField(decimal_places=2, default=0, help_text='km/h', max_digits=6)),
                ('wind_direction', models.CharField(blank=True, max_length=10, null=True)),
                ('condition', models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('windy', 'Windy'), ('foggy', 'Foggy'), ('thunderstorm', 'Thunderstorm')], default='sunny', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='farms.field')),
            ],
            options={
                'db_table': 'tbl_weather_data',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
