# Generated by Django 5.2.16 on 2026-09-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_field_district_field_state'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_image',
            field=models.FileField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='completion_image',
            field=models.FileField(blank=True, null=True, upload_to='complaints/completion/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='completion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='farms.field'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='progress',
            field=models.IntegerField(default=0, help_text='Percentage completed (0-100)'),
        ),
        migrations.AddField(
            model_name='complaintupdate',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('irrigation', 'Irrigation System Problem'), ('water_leakage', 'Water Leakage'), ('pump', 'Pump Problem'), ('pipe', 'Pipe Problem'), ('sprinkler', 'Sprinkler Problem'), ('drip', 'Drip System Problem'), ('watering', 'Field Watering Issue'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='status_changed_to',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
