# Generated by Django 5.2.16 on 2026-08-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='planting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
