# Generated by Django 5.2.16 on 2026-08-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_field_planting_date_field_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='state',
            field=models.CharField(blank=True, default='Kerala', max_length=100, null=True),
        ),
    ]
