# Generated by Django 5.2.16 on 2026-09-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_field_district_field_state'),
        ('master', '0003_cropvariety_cropwaterrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='crop_variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='master.cropvariety'),
        ),
    ]
