# Generated by Django 5.2.16 on 2026-08-14 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0003_field_district_field_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropHealthAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('possible_causes', models.JSONField(default=list)),
                ('fertilizer', models.JSONField(default=list)),
                ('watering_advice', models.TextField(blank=True)),
                ('prevention', models.JSONField(default=list)),
                ('confidence', models.IntegerField(default=85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_health_analyses', to='farms.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_health_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_crop_health_analysis_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
