# Generated by Django 5.2.16 on 2026-08-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crophealthanalysislog',
            name='status',
            field=models.CharField(default='Healthy', max_length=100),
        ),
    ]
