# Generated by Django 5.2.16 on 2026-08-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_health', '0002_crophealthanalysislog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crophealthanalysislog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_health_leaves/'),
        ),
        migrations.AddField(
            model_name='crophealthanalysislog',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text Analysis'), ('image', 'Image Analysis'), ('both', 'Text & Image Analysis')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='crophealthanalysislog',
            name='predicted_disease',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='crophealthanalysislog',
            name='confidence',
            field=models.FloatField(default=90.0),
        ),
        migrations.AlterField(
            model_name='crophealthanalysislog',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
