# Generated by Django 4.2 on 2026-07-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoistureEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_moisture', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('estimated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_estimations', to='farms.field')),
            ],
            options={
                'db_table': 'tbl_soil_moisture_estimation',
                'ordering': ['-estimated_at'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_status', models.CharField(choices=[('irrigate', 'Irrigate'), ('monitor', 'Monitor'), ('postpone', 'Postpone')], default='monitor', max_length=20)),
                ('recommended_volume_litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recommended_duration_minutes', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_recommendations', to='farms.field')),
            ],
            options={
                'db_table': 'tbl_irrigation_recommendation',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('priority_rank', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_priorities', to='farms.field')),
            ],
            options={
                'db_table': 'tbl_irrigation_priority',
                'ordering': ['priority_rank'],
            },
        ),
        migrations.CreateModel(
            name='CropStressRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('stress_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factors', models.JSONField(blank=True, default=dict, help_text='Dict of contributing factors')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_stress_records', to='farms.field')),
            ],
            options={
                'db_table': 'tbl_crop_stress_risk',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
