# Generated by Django 4.2 on 2026-07-29 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_mm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rainfall_confirmations', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_confirmations', to='farms.field')),
            ],
            options={
                'db_table': 'tbl_rainfall_confirmation',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('drip', 'Drip'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood'), ('manual', 'Manual'), ('surface', 'Surface')], default='drip', max_length=20)),
                ('water_source', models.CharField(choices=[('canal', 'Canal'), ('borewell', 'Borewell'), ('rain', 'Rainwater'), ('river', 'River'), ('tank', 'Tank')], default='canal', max_length=20)),
                ('volume_litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('irrigated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_history', to='farms.field')),
            ],
            options={
                'db_table': 'tbl_irrigation_history',
                'ordering': ['-irrigated_at'],
            },
        ),
    ]
