# Generated by Django 5.2.16 on 2026-08-01 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationhistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='irrigationhistory',
            name='field_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
