# Generated by Django 5.2.16 on 2026-08-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_irrigationhistory_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfallconfirmation',
            name='rainfall_option',
            field=models.CharField(choices=[('no_rain', 'No Rain'), ('light_rain', 'Light Rain'), ('moderate_rain', 'Moderate Rain'), ('heavy_rain', 'Heavy Rain')], default='no_rain', max_length=20),
        ),
        migrations.AlterField(
            model_name='rainfallconfirmation',
            name='rainfall_mm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
