# Generated by Django 5.2.17 on 2026-08-16 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_field_district_field_state'),
        ('irrigation', '0003_rainfallconfirmation_rainfall_option_and_more'),
        ('recommendation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('reservoir', 'Reservoir'), ('pond', 'Pond'), ('well', 'Well'), ('canal', 'Canal'), ('river', 'River'), ('rainwater', 'Rainwater Storage')], default='reservoir', max_length=30)),
                ('location', models.CharField(help_text='District or Location (e.g. Pala, Kottayam)', max_length=100)),
                ('capacity_liters', models.DecimalField(decimal_places=2, help_text='Total storage capacity in liters', max_digits=14)),
                ('current_level_liters', models.DecimalField(decimal_places=2, help_text='Current stored water in liters', max_digits=14)),
                ('reserved_liters', models.DecimalField(decimal_places=2, default=0, help_text='Water reserved for allocations', max_digits=14)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_water_source',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterAllocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount_liters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partially_approved', 'Partially Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('reason', models.TextField(blank=True, help_text='Reason for rejection or approval notes', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_requests', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_requests', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_requests', to='farms.field')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendation.irrigationrecommendation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_water_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_water_allocation_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_level_liters', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_level_liters', models.DecimalField(decimal_places=2, max_digits=14)),
                ('change_amount_liters', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='irrigation.watersource')),
            ],
            options={
                'db_table': 'tbl_water_level_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount_liters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_amount_liters', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_allocations', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_allocations', to='farms.farm')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_allocations', to='farms.field')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='irrigation.waterallocationrequest')),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='irrigation.watersource')),
            ],
            options={
                'db_table': 'tbl_water_allocation',
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_liters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='irrigation.waterallocation')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_usages', to='farms.field')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='irrigation.watersource')),
            ],
            options={
                'db_table': 'tbl_water_usage',
                'ordering': ['-used_at'],
            },
        ),
    ]
