# Generated by Django 5.2.16 on 2026-09-08 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_field_district_field_state'),
        ('irrigation', '0004_watersource_waterallocationrequest_waterlevelhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationhistory',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_records', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='irrigationhistory',
            name='recommended_water_litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='irrigationhistory',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('not_done', 'Not Done')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='irrigationhistory',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='irrigationhistory',
            name='volume_litres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
