# Generated by Django 5.2.16 on 2026-09-26 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0005_irrigationhistory_farm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waterallocationrequest',
            name='supervisor_notes',
            field=models.TextField(blank=True, help_text='Notes recorded during supervisor field verification', null=True),
        ),
        migrations.AddField(
            model_name='waterallocationrequest',
            name='supervisor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterallocationrequest',
            name='supervisor_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending_review', max_length=25),
        ),
        migrations.AddField(
            model_name='waterallocationrequest',
            name='verified_by_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_verified_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
