# Generated by Django 5.2.16 on 2026-08-14 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0003_field_district_field_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrigation_needed', models.BooleanField(default=False)),
                ('recommended_water_l_m2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('crop_stress', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
                ('confidence', models.IntegerField(default=0, help_text='Confidence percentage 0-100')),
                ('reason', models.TextField(blank=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rainfall', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('days_since_irrigation', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='farms.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='farms.field')),
            ],
            options={
                'db_table': 'tbl_ai_recommendation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
